---
- hosts: all
  become: yes
  gather_facts: yes

  tasks: 
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      tags:
          - apt_get
      when: ansible_os_family== "Debian"
    
    - name: Install httpd on redhat family
      yum: 
        name: httpd
        state: present
      when: ansible_os_family== "RedHat"

      
    - name: Create user serge
      user:
        name: Serge
        comment: Serge Smith
        shell: /bin/bash    
    - name: Create group
      group: 
        name: cloudteam
        state: present
    - name: create index file 
      file:
        path: /var/www/html/index.html
        state: touch
      register: file_output
      tags:
        - create_file
    
    - name: Create directory
      file: 
        path: /tmp/os
        state: directory       

    - name: copy content to index
      copy: 
        dest: file_output.diff.before.path
        content: '<h1>This is created using Ansible' 
