---
- hosts: ws
  become: 1
  gather_facts: 1
  ignore_errors: true
  tasks:
    - name: Package Install
      apt:
        name: "{{item}}"
        state: present
      loop:
        - wget
         - finger
         - curl
