---
- hosts: db
  become: yes
  become_user: root
  ignore_errors: yes
  tasks:
    - name: Install packages
      apt:
       state: present
       name:
       - docker
       - wget
       - lsof
       - unzip
       - passwd
       - java-11*
    
    - name: Create Directory
      file:
       path: /opt/qa/spg
       state: directory

    - name:  create log file 
      file:
        path: /opt/qa/spg/spg.log
        state: touch

    - name: start and enable daemon
      systemd:
        name: docker
        state: started
        enabled: yes
             