---
- hosts: db
  become: yes
  become_user: root
  ignore_errors: yes
  tasks:
    - name: Install python3 and python3-apt
      raw: |
        apt-get update
        apt-get install -y python3 python3-apt
      register: result
      changed_when: "'installed' in result.stdout or 'upgraded' in result.stdout"

    - name: Install packages
      apt:
       state: present
       name:
       - docker
       - wget
       - lsof
       - unzip
       - passwd
       - java-11*
    
    - name: Create Directory
      file:
       path: /opt/qa/spg
       state: directory

    - name:  create log file 
      file:
        path: /opt/qa/spg/spg.log
        state: touch

    - name: start and enable daemon
      systemd:
        name: docker
        state: started
        enabled: yes
             